import React from 'react'
import type { Meta, StoryObj } from '@storybook/react'
import { Microcopy } from './Microcopy'
import { AiIcon } from '../../icons'

const meta: Meta<typeof Microcopy> = {
  title: 'Design System/Microcopy',
  tags: ['autodocs'],
  component: Microcopy,
}
export default meta

type Story = StoryObj<typeof Microcopy>

export const Default: Story = {
  args: {
    on: 'surface',
    icon: <AiIcon sx={{ color: 'on.surface.accent' }} />,
    message: 'Generated by Artificial Intelligence',
  },
}
