services:
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role_api == true
    update_config:
      parallelism: 1
      delay: 10s
    restart_policy:
      condition: on-failure

  web:
    extends:
      file: docker-compose.base.yml
      service: web
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role_web == true
    update_config:
      parallelism: 1
      delay: 10s
    restart_policy:
      condition: on-failure

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role_db == true
    update_config:
      parallelism: 1
      delay: 10s
    restart_policy:
      condition: on-failure

volumes:
  pgdata:
    driver: local