services:
  api:
    image: ${REGISTRY_IP_W_PORT}vegangouda-api:latest
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://testuser:testpassword@postgres:5432/vegangoudadb}
      JWT_SECRET: ${JWT_SECRET}
      SALT_KEY: ${SALT_KEY}
    ports:
      - target: 3000
        published: ${API_PORT:-3000}
        protocol: tcp
        mode: ingress
    networks:
      - webnet
      - dbnet
    deploy:
      replicas: ${API_REPLICAS:-1}
      placement:
        constraints:
          - node.labels.role_api == true
      update_config:
        parallelism: ${API_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure

  web:
    image: ${REGISTRY_IP_W_PORT}vegangouda-web:latest
    environment:
      API_URL: ${API_URL:-http://api:3000}
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: ingress
    networks:
      - webnet
    deploy:
      replicas: ${WEB_REPLICAS:-1}
      placement:
        constraints:
          - node.labels.role_web == true
      update_config:
        parallelism: ${WEB_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vegangoudadb}
      POSTGRES_USER: ${POSTGRES_USER:-testuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testpassword}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
        mode: ingress
    networks:
      - dbnet
    deploy:
      replicas: ${DB_REPLICAS:-1}
      placement:
        constraints:
          - node.labels.role_db == true
      update_config:
        parallelism: ${DB_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  webnet:
  dbnet:

volumes:
  pgdata:
    driver: local