version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  registry:
    image: registry:2
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      placement:
        constraints:
          - node.role == manager

  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    restart: unless-stopped
    volumes:
      - /mnt/nfs/raid:/nfsshare
    environment:
      - SHARED_DIRECTORY=/nfsshare
    ports:
      - '2049:2049'

volumes:
  portainer_data:
    driver: local
  registry_data:
    driver: local
