services:
  api:
    image: vegangouda-api:latest
    environment:
      DATABASE_URL: postgres://testuser:testpassword@vegangouda_postgres:5432/vegangoudadb
    ports:
      - '3000:3000'
    networks:
      - webnet
      - dbnet
    deploy:
      replicas: ${API_REPLICAS:-1}
      update_config:
        parallelism: ${API_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure

  web:
    image: vegangouda-web:latest
    ports:
      - '80:80'
    networks:
      - webnet
    deploy:
      replicas: ${WEB_REPLICAS:-1}
      update_config:
        parallelism: ${WEB_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: vegangoudadb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dbnet
    deploy:
      replicas: ${DB_REPLICAS:-1}
      update_config:
        parallelism: ${DB_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  webnet:
  dbnet:

volumes:
  pgdata:
    driver: local