/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface emailLogin {
  email: string;
  password: string;
}

export interface mobileLogin {
  code: string;
  mobile: string;
}

export interface user {
  archived: boolean;
  createdAt: Date;
  email: string;
  firstName: string;
  lastName: string;
  mobile: string;
  updatedAt: Date;
  user_id: string;
}

export interface userCreate {
  email: string;
  firstName: string;
  lastName: string;
  mobile: string;
  password: string;
}

export interface userUpdate {
  email: string;
  firstName: string;
  lastName: string;
  mobile: string;
  password: string;
}
